name: pharmalive
channels:
  - default
dependencies:
  - python=3.7.3
  - pip
  - pip :
      - flask
      - SQLAlchemy
      - Flask-SQLAlchemy
      - flask-cors
      - Flask-Bcrypt
      - jwt


