name: pharmalive
channels:
  - default
dependencies:
  - python=3.7.3
  - pip
  - pip:
      - flask
      - SQLAlchemy
      - flask-cors
      - Flask-Bcrypt
      - jwt
      - pyjwt
      - flask_sqlalchemy
      - flask-marshmallow
      - marshmallow-sqlalchemy
